plex-media-server:
  fullnameOverride: "pms"

  extraEnv:
    TZ: "America/Phoenix"

  service:
    type: LoadBalancer

  pms:
    configStorage: 30Gi

  # Volume definition
  # extraVolumeMounts:
  #   - mountPath: /data
  #     name: media-plex
  # extraVolumes:
  #   - name: media-plex
  #     accessMode: ReadWriteMany
  #     size: 300Gi

  
  ingress:
    enabled: true
    ingressClassName: nginx
    url: plex.pl4.me
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod
    hosts:
      - host: &host plex.pl4.me
        path: /
        pathType: Prefix
    tls:
      - secretName: plex-tls-certificate
        hosts:
          - *host