kube-plex:
  claimToken: "claim-emmFriUH7R_hP2ExojsY"
  timezone: "America/Phoenix"

  kubePlex:
    loglevel: "debug"
    resources:
      requests:
        gpu.intel.com/i915: 1
      limits:
        gpu.intel.com/i915: 2

  ingress:
    enabled: true
    ingressClass: nginx
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod
    hosts:
      - host: &host plex.pl4.me
        path: /
        pathType: Prefix
    tls:
      - secretName: plex-tls-certificate
        hosts:
          - *host

  persistence:
    transcode:
      enabled: true
      accessMode: ReadWriteMany
      size: 100Gi
    data:
      claimName: "kube-plex-data-nfs-pvc"
    config:
      accessMode: ReadWriteMany
      size: 20Gi