app-template:
  defaultPodOptions:
    securityContext:
      fsGroup: 1000
      supplementalGroups:
        - 105
  controllers:
    main:
      containers:
        main:
          image:
            repository: docker.io/plexinc/pms-docker
            tag: latest
          securityContext:
            privileged: true
            capabilities:
              add:
                - SYS_ADMIN
          resources:
            requests:
              gpu.intel.com/i915: 1
            limits:
              gpu.intel.com/i915: 1
          env:
            PLEX_CLAIM: "claim-tU7s_C4GXMvcU5wzUMbx"
            HOSTNAME: "plex.pl4.me"
            TZ: "America/Phoenix"
            ALLOWED_NETWORKS: "192.168.15.1/24"
  service:
    main:
      ports:
        http:
          port: 32400
          protocol: HTTP
    external:
      type: ClusterIP
      controller: main
      primary: false
      ports:
        plex-external:
          port: 32400
          protocol: TCP
    extraports:
      type: ClusterIP
      controller: main
      primary: false
      ports:
        plex-dlna:
          port: 1900
          protocol: TCP
        plex-dlna-udp:
          port: 32469
          protocol: UDP
        plex-bonjour:
          port: 5353
          protocol: UDP
        plex-roku:
          port: 8324
          protocol: TCP
        plex-gdm-1:
          port: 32410
          protocol: UDP
        plex-gdm-2:
          port: 32412
          protocol: UDP
        plex-gdm-3:
          port: 32413
          protocol: UDP
        plex-gdm-4:
          port: 32414
          protocol: UDP
  ingress:
    main:
      enabled: true
      className: nginx
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
      hosts:
        - host: &plexHost plex.pl4.me
          paths:
            - path: /
              pathType: Prefix
              service:
                name: main
                port: http
      tls:
        - secretName: plex-tls-certificate
          hosts:
            - *plexHost

  persistence:
    pms-transcodes:
      name: pms-transcodes
      type: emptyDir
      medium: Memory
      sizeLimit: 1Gi
      advancedMounts:
        main:
          main:
            - path: /transcode
    media:
      accessMode: ReadWriteOnce
      size: 500Gi
      storageClass: plex-nfs-csi
      advancedMounts:
        main:
          main:
            - path: /media/movies
              subPath: movies
            - path: /media/shows
              subPath: shows
    pms-config:
      accessMode: ReadWriteOnce
      size: 2Gi
      advancedMounts:
        main:
          main:
            - path: /config