app-template:
  defaultPodOptions:
    securityContext:
      fsGroup: 1000
      supplementalGroups:
        - 105
  controllers:
    main:
      containers:
        main:
          image:
            repository: docker.io/plexinc/pms-docker
            tag: latest
          securityContext:
            privileged: true
            capabilities:
              add:
                - SYS_ADMIN
          resources:
            requests:
              gpu.intel.com/i915: 1
            limits:
              gpu.intel.com/i915: 1
          env:
            PLEX_CLAIM: "claim-tU7s_C4GXMvcU5wzUMbx"
            HOSTNAME: "plex.pl4.me"
            TZ: "America/Phoenix"
            ALLOWED_NETWORKS: "192.168.15.1/24"
        qbittorrent:
          image:
            repository: docker.io/linuxserver/qbittorrent
            tag: 4.6.3-libtorrentv1
          env:
            WEBUI_PORT: 8090
        prowlarr:
          image:
            repository: lscr.io/linuxserver/prowlarr
            tag: 1.12.2
        radarr:
          image:
            repository: lscr.io/linuxserver/radarr
            tag: 5.2.6
        sonarr:
          image:
            repository: lscr.io/linuxserver/sonarr
            tag: 4.0.1
        overseerr:
          image:
            repository: lscr.io/linuxserver/overseerr
            tag: 1.33.2
        tautulli:
          image:
            repository: lscr.io/linuxserver/tautulli
            tag: 2.13.4
        organizr:
          image:
            repository: docker.io/organizr/organizr
            tag: latest
  service:
    main:
      ports:
        http:
          port: 32400
          protocol: HTTP
        qbittorrent:
          port: 8090
          protocol: HTTP
        prowlarr:
          port: 9696
          protocol: HTTP
        radarr:
          port: 7878
          protocol: HTTP
        sonarr:
          port: 8989
          protocol: HTTP
        overseerr:
          port: 5055
          protocol: HTTP
        tautulli:
          port: 8181
          protocol: HTTP
        organizr:
          port: 80 
          protocol: HTTP
    external:
      type: ClusterIP
      controller: main
      primary: false
      ports:
        plex-external:
          port: 32400
          protocol: TCP
    extraports:
      type: ClusterIP
      controller: main
      primary: false
      ports:
        plex-dlna:
          port: 1900
          protocol: TCP
        plex-dlna-udp:
          port: 32469
          protocol: UDP
        plex-bonjour:
          port: 5353
          protocol: UDP
        plex-roku:
          port: 8324
          protocol: TCP
        plex-gdm-1:
          port: 32410
          protocol: UDP
        plex-gdm-2:
          port: 32412
          protocol: UDP
        plex-gdm-3:
          port: 32413
          protocol: UDP
        plex-gdm-4:
          port: 32414
          protocol: UDP
  ingress:
    main:
      enabled: true
      className: nginx
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
      hosts:
        - host: &plexHost plex.pl4.me
          paths:
            - path: /
              pathType: Prefix
              service:
                name: main
                port: http
        - host: &qbittorrentHost qbittorrent.pl4.me
          paths:
            - path: /
              pathType: Prefix
              service:
                name: main
                port: qbittorrent
        - host: &prowlarrHost prowlarr.pl4.me
          paths:
            - path: /
              pathType: Prefix
              service:
                name: main
                port: prowlarr
        - host: &radarrHost radarr.pl4.me
          paths:
            - path: /
              pathType: Prefix
              service:
                name: main
                port: radarr
        - host: &sonarrHost sonarr.pl4.me
          paths:
            - path: /
              pathType: Prefix
              service:
                name: main
                port: sonarr
        - host: &overseerrHost overseerr.pl4.me
          paths:
            - path: /
              pathType: Prefix
              service:
                name: main
                port: overseerr
        - host: &tautulliHost tautulli.pl4.me
          paths:
            - path: /
              pathType: Prefix
              service:
                name: main
                port: tautulli                            
        - host: &organizrHost organizr.pl4.me
          paths:
            - path: /
              pathType: Prefix
              service:
                name: main
                port: organizr
      tls:
        - secretName: plex-tls-certificate
          hosts:
            - *plexHost
            - *qbittorrentHost
            - *prowlarrHost
            - *radarrHost
            - *sonarrHost
            - *overseerrHost
            - *tautulliHost
            - *organizrHost
  persistence:
    pms-transcodes:
      name: pms-transcodes
      type: emptyDir
      medium: Memory
      sizeLimit: 1Gi
      advancedMounts:
        main:
          main:
            - path: /transcode
    media:
      accessMode: ReadWriteOnce
      size: 500Gi
      storageClass: plex-nfs-csi
      advancedMounts:
        main:
          main:
            - path: /media/movies
              subPath: movies
            - path: /media/shows
              subPath: shows
            - path: /media/anime
              subPath: anime
          qbittorrent:
            - path: /downloads
              subPath: qbittorrent/downloads
          radarr:
            - path: /downloads
              subPath: qbittorrent/downloads
            - path: /movies
              subPath: movies
          sonarr:
            - path: /downloads
              subPath: qbittorrent/downloads
            - path: /shows
              subPath: shows
            - path: /anime
              subPath: anime
    pms-config:
      accessMode: ReadWriteOnce
      size: 2Gi
      annotations:
        "k8up.io/backup": true
      advancedMounts:
        main:
          main:
            - path: /config
    data:
      accessMode: ReadWriteOnce
      size: 50Gi
      annotations:
        "k8up.io/backup": true
      advancedMounts:
        main:
          qbittorrent:
            - path: /config
              subPath: qbittorrent/config
          prowlarr:
            - path: /config
              subPath: prowlarr/config
          radarr:
            - path: /config
              subPath: radarr/config
          sonarr:
            - path: /config
              subPath: sonarr/config
          overseerr:
            - path: /config
              subPath: overseerr/config
          tautulli:
            - path: /config
              subPath: tautulli/config
          organizr:
            - path: /config
              subPath: organizr/config