connect:
  connect:
    serviceType: ClusterIP
    credentialsName: onepassword-secret
    credentialsKey: credentials
  operator:
    create: true
    token:
      name: onepassword-secret

external-secrets:
  installCRDs: true