app-template:
  defaultPodOptions:
    securityContext:
      fsGroup: 1000
      supplementalGroups:
        - 105
  controllers:
    main:
      containers:
        main:
          image:
            repository: docker.io/pandabear41/jellyfin-clean-transcodes
            tag: 10.8.13
          securityContext:
            privileged: true
          volumeMounts:
            - name: intel-gpu
              mountPath: /dev/dri/renderD128
        transmission:
          image:
            repository: lscr.io/linuxserver/transmission
            tag: 4.0.5
        prowlarr:
          image:
            repository: lscr.io/linuxserver/prowlarr
            tag: 1.12.2
        radarr:
          image:
            repository: lscr.io/linuxserver/radarr
            tag: 5.2.6
        sonarr:
          image:
            repository: lscr.io/linuxserver/sonarr
            tag: 4.0.0
        jellyseerr:
          image:
            repository: docker.io/fallenbagel/jellyseerr
            tag: 1.7.0
  service:
    main:
      ports:
        http:
          port: 8096
          protocol: HTTP
        transmission:
          port: 9091
          protocol: HTTP
        prowlarr:
          port: 9696
          protocol: HTTP
        radarr:
          port: 7878
          protocol: HTTP
        sonarr:
          port: 8989
          protocol: HTTP
        jellyseerr:
          port: 5055
          protocol: HTTP
  ingress:
    main:
      enabled: true
      className: nginx
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
      hosts:
        - host: &jellyfinHost jellyfin.pl4.me
          paths:
            - path: /
              pathType: Prefix
              service:
                name: main
                port: http
        - host: &transmissionHost transmission.pl4.me
          paths:
            - path: /
              pathType: Prefix
              service:
                name: main
                port: transmission
        - host: &prowlarrHost prowlarr.pl4.me
          paths:
            - path: /
              pathType: Prefix
              service:
                name: main
                port: prowlarr
        - host: &radarrHost radarr.pl4.me
          paths:
            - path: /
              pathType: Prefix
              service:
                name: main
                port: radarr
        - host: &sonarrHost sonarr.pl4.me
          paths:
            - path: /
              pathType: Prefix
              service:
                name: main
                port: sonarr
        - host: &jellyseerrHost jellyseerr.pl4.me
          paths:
            - path: /
              pathType: Prefix
              service:
                name: main
                port: jellyseerr
      tls:
        - secretName: jellyfin-tls-certificate
          hosts:
            - *jellyfinHost
            - *transmissionHost
            - *prowlarrHost
            - *radarrHost
            - *sonarrHost
            - *jellyseerrHost
  persistence:
    intel-gpu:
      type: hostPath
      hostPath: /dev/dri/renderD128
    config-transcodes:
      name: config-transcodes
      type: emptyDir
      sizeLimit: 512Mi
      advancedMounts:
        main:
          main:
            path: /config/transcodes
    config-semaphore:
      name: config-semaphore
      type: emptyDir
      sizeLimit: 10Mi
      advancedMounts:
        main:
          main:
            path: /config/semaphore
    data:
      accessMode: ReadWriteOnce
      size: 50Gi
      advancedMounts:
        main:
          main:
            - path: /config
              subPath: jellyfin/config
            - path: /media/movies
              subPath: movies
            - path: /media/shows
              subPath: shows
          transmission:
            - path: /config
              subPath: transmission/config
            - path: /downloads
              subPath: transmission/downloads
          prowlarr:
            - path: /config
              subPath: prowlarr/config
          radarr:
            - path: /config
              subPath: radarr/config
            - path: /downloads/complete
              subPath: transmission/downloads/complete
            - path: /movies
              subPath: movies
          sonarr:
            - path: /config
              subPath: sonarr/config
            - path: /downloads/complete
              subPath: transmission/downloads/complete
            - path: /shows
              subPath: shows
          jellyseerr:
            - path: /app/config
              subPath: jellyseerr/config
