redis:
  auth:
    existingSecret: redis-auth-secret
    existingSecretPasswordKey: password
  master:
    persistence:
      size: 3Gi
  replica:
    persistence:
      size: 3Gi
  sentinel:
    enabled: true
    masterSet: redis-master
    getMasterTimeout: 10
    startupProbe:
      failureThreshold: 2
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true
      interval: 1m

redisinsight:
  controllers:
    main:
      containers:
        main:
          image:
            repository: docker.io/redislabs/redisinsight
            tag: 1.14.0
  
  serviceAccount:
    create: true
    name: redisinsight

  service:
    main:
      ports:
        http:
          port: 8001
          protocol: HTTP

  ingress:
    main:
      enabled: true
      className: nginx
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
      hosts:
        - host: &host redisinsights.pl4.me
          paths:
            - path: /
              pathType: Prefix
              service:
                name: main
                port: http    
      tls:
        - secretName: redisinsights-tls-certificate
          hosts:
            - *host