redis:
  auth:
    existingSecret: redis-auth-secret
    existingSecretPasswordKey: password
  master:
    persistence:
      size: 3Gi
  replica:
    persistence:
      size: 3Gi
  sentinel:
    enabled: true
    masterSet: redis-master
    getMasterTimeout: 10
    startupProbe:
      failureThreshold: 2
  metrics:
    enabled: false
    # serviceMonitor:
    #   enabled: true
    #   interval: 1m

redisinsight:
  global:
    nameOverride: redisinsight

  controllers:
    main:
      containers:
        main:
          image:
            repository: docker.io/redis/redisinsight
            tag: 2.42
          env:
            RI_APP_HOST: redis-headless.redis.svc.cluster.local
  
  serviceAccount:
    create: true
    name: redisinsight

  persistance:
    data:
      enabled: true
      accessMode: ReadWriteOnce
      size: 250Mi

  service:
    main:
      ports:
        http:
          port: 5540
          protocol: HTTP

  ingress:
    main:
      enabled: true
      className: nginx
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
      hosts:
        - host: &host redisinsights.pl4.me
          paths:
            - path: /
              pathType: Prefix
              service:
                name: main
                port: http    
      tls:
        - secretName: redisinsights-tls-certificate
          hosts:
            - *host