---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: plex-nfs-media
spec:
  capacity:
    storage: 500Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: plex-nfs-media
  
  mountOptions:
    - nfsvers=4
  csi:
    driver: nfs.csi.k8s.io
    readOnly: false
    volumeHandle: plex-nfs-media
    volumeAttributes:
      server: 192.168.16.30
      share: /plex
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: plex-nfs-media
  annotations:
    'k8up.io/backup': 'false'
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 500Gi
  volumeName: plex-nfs-media
  storageClassName: plex-nfs-media