---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: plex-nfs-csi
provisioner: nfs.csi.k8s.io
parameters:
  server: 192.168.16.30
  share: /plex
  # csi.storage.k8s.io/provisioner-secret is only needed for providing mountOptions in DeleteVolume
  # csi.storage.k8s.io/provisioner-secret-name: "mount-options"
  # csi.storage.k8s.io/provisioner-secret-namespace: "default"
reclaimPolicy: Retain
volumeBindingMode: Immediate
mountOptions:
  - nfsvers=4.1
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: plex-nfs-media
  annotations:
    'k8up.io/backup': 'false'
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 500Gi
  storageClassName: plex-nfs-media