cilium_repo_url: https://helm.cilium.io
cilium_version: 1.15.0-rc.1 # TODO switch to stable release
cilium_namespace: kube-system
cilium_values:
  operator:
    replicas: 1
  kubeProxyReplacement: true
  l2announcements:
    enabled: true
  # TODO the host and port are k3s-specific, generic solution is in progress
  # https://github.com/cilium/cilium/issues/19038
  # https://github.com/cilium/cilium/pull/28741
  k8sServiceHost: 127.0.0.1
  k8sServicePort: 6444
  routingMode: native
  containerRuntime:
    integration: containerd
    socketPath: /var/run/k3s/containerd/containerd.sock
  autoDirectNodeRoutes: true
  bandwidthManager:
    enabled: true
    bbr: false
  bpf:
    masquerade: true
  bgp:
    enabled: false
  cluster:
    name: kubernetes
    id: 1
  ipam:
    mode: kubernetes
  endpointRoutes:
    enabled: true
  ipv4:
    enabled: true
  ipv6:
    enabled: false
  ipv4NativeRoutingCIDR: 10.42.0.0/16
