all:
  vars:
    control_plane_endpoint: 10.10.10.200
    load_balancer_ip_pool:
      - 10.10.10.224/27
metal:
  children:
    masters:
      hosts:
        metal0: {ansible_host: 10.10.10.100, mac: '00:4e:01:a5:fb:5f', disk: nvme0n1, network_interface: eno2}
        metal1: {ansible_host: 10.10.10.101, mac: '8c:04:ba:9c:5b:83', disk: nvme0n1, network_interface: eno2}
        # metal2: {ansible_host: 192.168.1.112, mac: '00:23:24:e7:04:60', disk: sda, network_interface: eno1}
    workers:
      hosts:
      # metal3: {ansible_host: 192.168.1.113, mac: '00:23:24:d1:f4:d6', disk: sda, network_interface: eno1}
