
- name: Remove Cilium resources - CiliumL2AnnouncementPolicy
  kubernetes.core.k8s:
    state: absent
    api_version: cilium.io/v2alpha1
    kind: CiliumL2AnnouncementPolicy
    namespace: {{ cilium_namespace }}
    name: default

- name: Remove Cilium resources - CiliumLoadBalancerIPPool
  kubernetes.core.k8s:
    state: absent
    api_version: v2alpha1
    kind: CiliumLoadBalancerIPPool
    namespace: {{ cilium_namespace }}
    name: default

- name: uninstall Cilium
  kubernetes.core.helm:
    state: absent
    name: cilium
    chart_ref: cilium
    namespace: "{{ cilium_namespace }}"
    wait: true

# - name: Install Cilium
#   kubernetes.core.helm:
#     name: cilium
#     chart_ref: cilium
#     chart_repo_url: "{{ cilium_repo_url }}"
#     chart_version: "{{ cilium_version }}"
#     release_namespace: "{{ cilium_namespace }}"
#     values: "{{ cilium_values }}"

# - name: Wait for Cilium CRDs
#   kubernetes.core.k8s_info:
#     kind: CustomResourceDefinition
#     name: "{{ item }}"
#   loop:
#     - ciliuml2announcementpolicies.cilium.io
#     - ciliumloadbalancerippools.cilium.io
#   register: crd
#   until: crd.resources | length > 0
#   retries: 5
#   delay: 10

# - name: Apply Cilium resources
#   kubernetes.core.k8s:
#     template: "{{ item }}"
#   loop:
#     - ciliuml2announcementpolicy.yaml
#     - ciliumloadbalancerippool.yaml
