- name: Install Calico
  kubernetes.core.helm:
    name: calico
    chart_ref: tigera-operator
    chart_repo_url: "{{ calico_repo_url }}"
    chart_version: "{{ calico_version }}"
    release_namespace: "{{ calico_namespace }}"
    values: "{{ calico_values }}"

- name: Wait for Calico CRDs
  kubernetes.core.k8s_info:
    kind: CustomResourceDefinition
    name: "{{ item }}"
  loop:
    - installations.operator.tigera.io
    - ipamconfigs.crd.projectcalico.org
  register: crd
  until: crd.resources | length > 0
  retries: 5
  delay: 10

- name: Apply Calico resources
  kubernetes.core.k8s:
    template: "{{ item }}"
  loop:
    - kubernetes-services-endpoint.yaml
    - kubernetes-services-endpoint-2.yaml