nextcloud:
  nextcloud:
    host: &host nextcloud.pl4.me
  ingress:
    enabled: true
    className: nginx
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod
      nginx.ingress.kubernetes.io/enable-cors: "true"
      nginx.ingress.kubernetes.io/cors-allow-headers: "X-Forwarded-For"
    tls:
      - secretName: nextcloud-tls-certificate
        hosts:
          - *host
  persistence:
    enabled: true
    size: 100Gi
