nextcloud:
  # Controller
  nextcloud:
    host: &host nextcloud.pl4.me
    phpConfigs:
      redis-cluster.ini: |-
        ; -- Redis session handler
        session.save_handler = redis
        session.save_path = "tcp://${REDIS_HOST}:${REDIS_HOST_PORT}?auth=${REDIS_HOST_PASSWORD}"
        redis.session.locking_enabled = 1
        redis.session.lock_retries = -1
        redis.session.lock_wait_time = 10000

    configs:
      proxy.config.php: |-
        <?php
        $CONFIG = array (
          'trusted_proxies' => array(
            0 => '127.0.0.1',
            1 => '10.0.0.0/8',
          ),
          'forwarded_for_headers' => array('HTTP_X_FORWARDED_FOR'),
        );
      redis-cluster.config.php: |-
        <?php 
        $CONFIG = [
          'memcache.local' => '\OC\Memcache\APCu',
          'memcache.distributed' => '\\OC\\Memcache\\Redis',
          'memcache.locking' => '\\OC\\Memcache\\Redis',
          'redis' => [
            'host' => getenv('REDIS_HOST'),
            'port' => getenv('REDIS_HOST_PORT') ?: 6379,
            'password' => getenv('REDIS_HOST_PASSWORD')
          ],
        ];

    extraEnv:
      - name: REDIS_HOST
        value: "dragonfly.nextcloud.svc.cluster.local"
      - name: REDIS_HOST_PORT
        value: "6379"
      - name: REDIS_HOST_PASSWORD
        valueFrom:
          secretKeyRef:
            name: dragonfly-secret
            key: DFLY_PASSWORD
  
  # Database
  internalDatabase:
    enabled: false
  externalDatabase:
    enabled: true
    type: postgresql
    existingSecret: 
      enabled: true
      secretName: database-nextcloud-user
      usernameKey: LOGIN
      passwordKey: PASSWORD
      hostKey: HOST
      databaseKey: DATABASE_NAME

  # Other Config
  livenessProbe:
    enabled: false
  readinessProbe:
    enabled: false
  redis:
    enabled: false
    # master:
    #   persistence:
    #     enabled: false
    # replica:
    #   persistence:
    #     enabled: false
  cronjob:
    enabled: true

  # Storage
  persistence:
    enabled: true
    size: 10Gi
    nextcloudData:
      enabled: true
      size: 100Gi

  # Ingress
  ingress:
    enabled: true
    className: nginx
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod
      nginx.ingress.kubernetes.io/enable-cors: "true"
      nginx.ingress.kubernetes.io/cors-allow-headers: "X-Forwarded-For"
      nginx.ingress.kubernetes.io/server-snippet: |-
        server_tokens off;
        proxy_hide_header X-Powered-By;
        rewrite ^/.well-known/webfinger /index.php/.well-known/webfinger last;
        rewrite ^/.well-known/nodeinfo /index.php/.well-known/nodeinfo last;
        rewrite ^/.well-known/host-meta /public.php?service=host-meta last;
        rewrite ^/.well-known/host-meta.json /public.php?service=host-meta-json;
        location = /.well-known/carddav {
          return 301 $scheme://$host/remote.php/dav;
        }
        location = /.well-known/caldav {
          return 301 $scheme://$host/remote.php/dav;
        }
        location = /robots.txt {
          allow all;
          log_not_found off;
          access_log off;
        }
        location ~ ^/(?:build|tests|config|lib|3rdparty|templates|data)/ {
          deny all;
        }
        location ~ ^/(?:autotest|occ|issue|indie|db_|console) {
          deny all;
        }
    tls:
      - secretName: nextcloud-tls-certificate
        hosts:
          - *host

dragonfly:
  global:
    nameOverride: dragonfly

  defaultPodOptions:
    securityContext:
      fsGroup: 1000

  controllers:
    main:
      type: statefulset
      replicas: 1

      containers:
        main:
          image: 
            repository: ghcr.io/dragonflydb/dragonfly
            tag: v1.14.1
          args:
            - --default_lua_flags=allow-undeclared-keys
            - --dir=/data
          env:
            DFLY_requirepass:
              valueFrom:
                secretKeyRef:
                  name: dragonfly-secret
                  key: DFLY_PASSWORD
          securityContext:
            capabilities:
              drop:
                - ALL
            readOnlyRootFilesystem: true
          
          probes:
            startup:
              enabled: false
            liveness:
              enabled: false
            readiness:
              enabled: false

  persistence:
    data:
      enabled: true
      accessMode: ReadWriteOnce
      size: 128Mi

  serviceAccount:
    create: true
  
  service:
    main:
      enabled: true
      ports:
        http:
          enabled: false
        redis:
          protocol: TCP
          port: 6379