renovate:
  cronjob:
    schedule: '*/5 * * * *'  # Everyday at 09:00
  renovate:
    config: |
      {
        "platform": "gitea",
        "endpoint": "https://git.pl4.me/api/v1",
        "gitAuthor": "Renovate Bot <bot@renovateapp.com>",
        "autodiscover": true
      }
  existingSecret: renovate-secret
