pod-gateway:
  image:
    repository: ghcr.io/angelnu/pod-gateway
    tag: v1.10.0
  settings:
    # VPN_INTERFACE: wg0
    VPN_BLOCK_OTHER_TRAFFIC: false
    VPN_TRAFFIC_PORT: 1443
    # NOT_ROUTED_TO_GATEWAY_CIDRS: "10.42.0.0/16 10.43.0.0/16"
    VPN_LOCAL_CIDRS: "10.0.0.0/8 192.168.0.0/16"
    # IPTABLES_NFT: yes
    # SNAT_IP: "10.168.100.85"
  # webhook:
  #   gatewayDefault: false
  #   image:
  #     repository: ghcr.io/angelnu/gateway-admision-controller
  #     tag: v3.10.0
    # publicPorts:
    #   - IP: 10
    #     hostname: qbittorrent
    #     ports:
    #       - port: 20294
    #         type: udp
    #       - port: 20294
    #         type: tcp
  addons:
    vpn:
      enabled: true
      type: gluetun
      gluetun:
        image:
          repository: docker.io/qmcgaw/gluetun
          tag: v3.37.0
      env:
        - name: WIREGUARD_MTU
          value: "1390"
        - name: FIREWALL
          value: "off"
        - name: DOT
          value: "off"
      envFrom:
        - secretRef:
            name: wireguard-config
      securityContext:
        capabilities:
          add: [ "NET_ADMIN" ]
      networkPolicy:
        enabled: true
        egress:
          - to:
              - ipBlock:
                  cidr: 0.0.0.0/0
            ports:
              - port: 1443
                protocol: UDP
          - to:
              - namespaceSelector: {}
          - to:
            - ipBlock:
                cidr: 10.0.0.0/8
      # livenessProbe:
      #   exec:
      #     command:
      #       - sh
      #       - -c
      #       - if [ $(wget -q -O- https://ipinfo.io/country) == 'NL' ]; then exit 0; else exit $?; fi
      #   initialDelaySeconds: 30
      #   periodSeconds: 60
      #   failureThreshold: 1