pod-gateway:
  image:
    repository: ghcr.io/angelnu/pod-gateway
    tag: v1.10.0
  routed_namespaces:
    - plex
    - vpn-proxy
  settings:
    # VPN_INTERFACE: wg0
    VPN_BLOCK_OTHER_TRAFFIC: false
    VPN_TRAFFIC_PORT: 1443
    NOT_ROUTED_TO_GATEWAY_CIDRS: "10.0.0.0/8 192.168.0.0/16"
    VPN_LOCAL_CIDRS: "10.0.0.0/8 192.168.0.0/16"
    # IPTABLES_NFT: yes
    # SNAT_IP: "10.13.128.81"
  webhook:
    # gatewayDefault: false
    image:
      repository: ghcr.io/angelnu/gateway-admision-controller
      tag: v3.10.0
    # publicPorts:
    #   - IP: 10
    #     hostname: qbittorrent
    #     ports:
    #       - port: 20294
    #         type: udp
    #       - port: 20294
    #         type: tcp
  addons:
    vpn:
      enabled: true
      type: gluetun
      gluetun:
        image:
          repository: docker.io/qmcgaw/gluetun
          tag: v3.37.0
      env:
        - name: WIREGUARD_MTU
          value: "1390"
        - name: DOT
          value: "off"
        - name: FIREWALL_VPN_INPUT_PORTS
          value: "20294"
      envFrom:
        - secretRef:
            name: wireguard-config
      securityContext:
        capabilities:
          add: [ "NET_ADMIN" ]
      networkPolicy:
        enabled: true
        egress:
          - to:
              - ipBlock:
                  cidr: 0.0.0.0/0
            ports:
              - port: 1443
                protocol: UDP
          - to:
            - namespaceSelector: {}
      livenessProbe:
        exec:
          command:
            - sh
            - -c
            - if [ $(wget -q -O- http://ip-api.com/line/?fields=countryCode) == 'RO' ]; then exit 0; else exit $?; fi
        initialDelaySeconds: 30
        periodSeconds: 300
        failureThreshold: 1