app-template:
  controllers:
    main:
      containers:
        main:
          image:
            repository: docker.io/kittyandrew/grafana-to-ntfy
            tag: latest
          env:
            BAUTH_USER: admin
          envFrom:
            - secret: "{{ .Release.Name }}-secret"
  service:
    main:
      ports:
        http:
          port: 80
          targetPort: 8080
          protocol: HTTP
