pihole:
  replicaCount: 1

  podAnnotations: 
    prometheus.io/port: '9617'
    prometheus.io/scrape: 'true'

  ingress:
    enabled: true
    ingressClassName: nginx
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod
    hosts:
      - &host pi-hole.pl4.me
    tls:
      - secretName: pi-hole-tls-certificate
        hosts:
          - *host
  
  virtualHost: *host

  persistentVolumeClaim:
    enabled: true

  serviceDns:
    loadBalancerIP: 10.10.10.250
    annotations:
      purelb.io/allow-shared-ip: piholesvc
    type: LoadBalancer
    externalTrafficPolicy: Cluster

  serviceDhcp:
    loadBalancerIP: 10.10.10.250
    annotations:
      purelb.io/allow-shared-ip: piholesvc
    type: LoadBalancer
    externalTrafficPolicy: Cluster
  
  serviceWeb:
    https:
      enabled: false

  podDnsConfig:
    enabled: true
    policy: "None"
    nameservers:
    - 127.0.0.1
    - 8.8.8.8
    - 8.8.4.4

  admin:
    existingSecret: "pihole-secret" 
    passwordKey: "PRIMARY_HOST_PASSWORD"

  monitoring:
    sidecar:
      enabled: true

  resources:
    limits:
      cpu: 400m
      memory: 384Mi
    requests:
      cpu: 100m
      memory: 128Mi

  extraEnvVars: {
    DNSMASQ_USER: "root"
  }

orbital-sync:
  controllers:
    main:
      containers:
        main:
          image:
            repository: ghcr.io/mattwebbio/orbital-sync
            tag: 1.5
          env:
            TZ: "America/Phoenix"
            PRIMARY_HOST_BASE_URL: "pihole-web.pihole.svc.cluster.local"
            INTERVAL_MINUTES: 30
          envFrom:
            - secretRef:
                name: orbital-sync-config
            - secretRef:
                name: pihole-secret
