pihole:
  replicaCount: 2

  topologySpreadConstraints:
    - maxSkew: 1
      topologyKey: kubernetes.io/hostname
      whenUnsatisfiable: DoNotSchedule

  image:
    repository: docker.io/pihole/pihole

  podAnnotations: 
    prometheus.io/port: '9617'
    prometheus.io/scrape: 'true'

  ingress:
    enabled: true
    ingressClassName: nginx
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod
    hosts:
      - &host pi-hole.pl4.me
    tls:
      - secretName: pi-hole-tls-certificate
        hosts:
          - *host
  
  virtualHost: *host

  # dnsHostPort:
  #   enabled: true

  persistentVolumeClaim:
    enabled: true
    accessModes:
      - ReadWriteMany

  serviceDns:
    loadBalancerIP: 10.10.10.250
    annotations:
      purelb.io/allow-shared-ip: piholesvc
    type: LoadBalancer
    externalTrafficPolicy: Cluster

  serviceDhcp:
    loadBalancerIP: 10.10.10.250
    annotations:
      purelb.io/allow-shared-ip: piholesvc
    type: LoadBalancer
    externalTrafficPolicy: Cluster
  
  serviceWeb:
    https:
      enabled: false

  podDnsConfig:
    enabled: true
    policy: "None"
    nameservers:
    - 127.0.0.1
    - 8.8.8.8
    - 8.8.4.4

  admin:
    existingSecret: "pihole-secret" 
    passwordKey: "PRIMARY_HOST_PASSWORD"

  monitoring:
    sidecar:
      enabled: false

  resources:
    limits:
      cpu: 400m
      memory: 384Mi
    requests:
      cpu: 100m
      memory: 128Mi

  extraEnvVars: 
    DNSMASQ_USER: "root"
    TZ: "America/Phoenix"
  
  # Doesn't work with replicas.
  # extraContainers:
  #   - name: pihole-orbital-sync
  #     image: ghcr.io/mattwebbio/orbital-sync:1.5
  #     command:
  #       - sh
  #       - -c
  #     args:
  #       - |
  #         sleep 90
  #         node dist/index.js
  #     env:
  #       - name: "TZ"
  #         value: "America/Phoenix"
  #       - name: "PRIMARY_HOST_BASE_URL"
  #         value: "https://pi-hole.pl4.me"
  #       - name: "INTERVAL_MINUTES"
  #         value: "30"
  #     envFrom:
  #       - secretRef:
  #           name: orbital-sync-config
  #       - secretRef:
  #           name: pihole-secret
