apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: database-cluster
spec:
  instances: 1
  imageName: ghcr.io/tensorchord/cloudnative-pgvecto.rs:16.1-v0.1.13
  postgresql:
    shared_preload_libraries:
      - "vectors.so"
  primaryUpdateStrategy: unsupervised
  storage:
    size: 10Gi
  superuserSecret:
    name: postgres-secret
  enableSuperuserAccess: true
  backup:
    barmanObjectStore:
      destinationPath: s3://pl4-homelab-database/
      endpointURL: https://s3.us-west-000.backblazeb2.com
      serverName: database-cluster-a
      s3Credentials:
        accessKeyId:
          name: backblaze-db
          key: ACCESS_KEY_ID
        secretAccessKey:
          name: backblaze-db
          key: ACCESS_SECRET_KEY
      wal:
        compression: gzip
        encryption: AES256
      data:
        compression: gzip
        encryption: AES256
    retentionPolicy: "90d"
  monitoring:
    enablePodMonitor: true