# Gitea
- name: gitea.admin
  data:
    - key: password
      length: 32
      special: true

# Dex
- name: dex.grafana
  data:
    - key: client_secret
      length: 32
      special: false
- name: dex.gitea
  data:
    - key: client_secret
      length: 32
      special: false

# Registry
- name: registry.admin
  data:
    - key: password
      length: 32
      special: true

# Woodpecker
- name: woodpecker.agent
  data:
    - key: secret
      length: 32
      special: false

# Paperless
- name: paperless.admin
  data:
    - key: PAPERLESS_ADMIN_PASSWORD
      length: 32
      special: true

# pihole
- name: pihole.admin
  data:
    - key: PASSWORD
      length: 32
      special: true

# ntfy
- name: ntfy-relay.auth
  data:
    - key: password
      length: 32
      special: true

# pgadmin4
- name: pgadmin4.admin
  data:
    - key: password
      length: 32
      special: true

# redis
- name: redis.auth
  data:
    - key: password
      length: 32
      special: true

