coder:  
  coder:
    # You can specify any environment variables you'd like to pass to Coder
    # here. Coder consumes environment variables listed in
    # `coder server --help`, and these environment variables are also passed
    # to the workspace provisioner (so you can consume them in your Terraform
    # templates for auth keys etc.).
    #
    # Please keep in mind that you should not set `CODER_ADDRESS`,
    # `CODER_TLS_ENABLE`, `CODER_TLS_CERT_FILE` or `CODER_TLS_KEY_FILE` as
    # they are already set by the Helm chart and will cause conflicts.
    env:
      - name: CODER_ACCESS_URL
        value: "https://coder.pl4.me"
      - name: CODER_PG_CONNECTION_URL
        valueFrom:
          secretKeyRef:
            # You'll need to create a secret called coder-db-url with your
            # Postgres connection URL like:
            # postgres://coder:password@postgres:5432/coder?sslmode=disable
            name: coder-db-url
            key: url

      # This env enables the Prometheus metrics endpoint.
      # - name: CODER_PROMETHEUS_ADDRESS
      #   value: "0.0.0.0:2112"
    # tls:
    #   secretNames:
    #     - my-tls-secret-name
    ingress:
      enable: true
      className: nginx
      host: coder.pl4.me
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
      tls:
        enable: true
        secretName: "coder-tls-certificate"