pihole:
  ingress:
    enabled: true
    ingressClassName: nginx
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod
    hosts:
    - &host pihole.pl4.me
    tls:
      - secretName: pihole-tls-certificate
        hosts:
          - *host

  persistentVolumeClaim:
    enabled: true

  serviceDns:
    annotations:
      "lbipam.cilium.io/sharing-key": "piholesvc"
    type: LoadBalancer

  serviceDhcp:
    annotations:
      "lbipam.cilium.io/sharing-key": "piholesvc"
    type: LoadBalancer

  podDnsConfig:
    enabled: true
    policy: "None"
    nameservers:
    - 127.0.0.1
    - 8.8.8.8
    - 8.8.4.4

  admin:
    existingSecret: "pihole-secret" 
    passwordKey: "PASSWORD"

  resources:
    limits:
      cpu: 200m
      memory: 256Mi
    requests:
      cpu: 100m
      memory: 128Mi

  extraEnvVars: {
    DNSMASQ_USER: "root"
  }