pihole:
  ingress:
    enabled: true

  persistentVolumeClaim:
    enabled: true

  serviceWeb:
    loadBalancerIP: 10.10.10.240
    annotations:
      "lbipam.cilium.io/sharing-key": "piholesvc"
    type: LoadBalancer

  serviceDns:
    annotations:
      "lbipam.cilium.io/sharing-key": "piholesvc"
    type: LoadBalancer

  serviceDhcp:
    annotations:
      "lbipam.cilium.io/sharing-key": "piholesvc"
    type: LoadBalancer

  podDnsConfig:
    enabled: true
    policy: "None"
    nameservers:
    - 127.0.0.1
    - 8.8.8.8
    - 8.8.4.4

  admin:
    existingSecret: "pihole.admin" 
    passwordKey: "PASSWORD"

  resources:
    limits:
      cpu: 200m
      memory: 256Mi
    requests:
      cpu: 100m
      memory: 128Mi

  extraEnvVars: {
    DNSMASQ_USER: "root"
  }