apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: authelia-users
  namespace: {{ .Release.Namespace }}
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: global-secrets
  data:
    - secretKey: database.yaml
      remoteRef:
        key: authelia.users
        property: database.yaml
