ingress-nginx:
  controller:
    admissionWebhooks:
      timeoutSeconds: 30
    metrics:
      enabled: true
      serviceMonitor:
        enabled: true
  tcp:
    22: gitea/gitea-ssh:22
    51413: jellyfin/jellyfin-seed:51413
  udp:
    51413: jellyfin/jellyfin-seed:51413
