ingress-nginx:
  controller:
    # disable for now.
    # autoscaling:
    #   enabled: true
    #   minReplicas: 2
    #   maxReplicas: 5
    allowSnippetAnnotations: true
    service:
      annotations:
        "lbipam.cilium.io/ips": "10.10.10.225" 
    admissionWebhooks:
      timeoutSeconds: 30
    metrics:
      enabled: true
      serviceMonitor:
        enabled: true
  tcp:
    22: gitea/gitea-ssh:22
    8324: plex/plex-extraports:8324
    32469: plex/plex-extraports:32469
  udp:
    32410: plex/plex-extraports:32410
    32412: plex/plex-extraports:32412
    32413: plex/plex-extraports:32413
    32414: plex/plex-extraports:32414
    1900: plex/plex-extraports:1900
